name: Deploy static files to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Deploy static files to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GBWebApp-03'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_58B6A92A1D32497292CEE7D965C11775 }}
          package: .
      # Step 3: Run Smoke Test    
      - name: Run Smoke Test
        run: |
          curl -I https://gbwebapp-03.azurewebsites.net | grep "200 OK"
